### ISSUE TITLE
Auto Display Label is rounding to far.  Example: $370.5m Auto displays to $0.4bn.  Can you only go to the next unit when reaching the thousands placement.

### ISSUE THREAD

**Issue by TXFidelis** [bhavesh-jadav/Advance-Card#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bhavesh-jadav** [comment]
I am using formatting utility made by Power BI team to auto format numbers. I will contact them regarding this issue and try to find the solution for it.

**Comment by RicardoMadaleno** [comment]
Hi,
I'm experiencing the same situation, but the strange thing is that it doesn't happen with the Power Bi default card...
do you think there will be a solution for this?
![advanced card rounding](https://user-images.githubusercontent.com/37866373/44264399-5c86fd00-a21a-11e8-925a-c87eb6fa3f77.gif)

**Comment by vichus1995** [comment]
yup,same issue for me. Auto display data label rounds 443K to 0M. 

![image](https://user-images.githubusercontent.com/16443214/44328001-031f0800-a47e-11e8-97e2-c10dde3141a6.png)

**Comment by vichus1995** [comment]
Same problem for me. auto display data label rounds 425K to 0M. 
![image](https://user-images.githubusercontent.com/16443214/44328111-55602900-a47e-11e8-9dc5-079993bfbd43.png)

**Comment by bhavesh-jadav** [comment]
I have fixed this issue in v1.1.1 and it will be available on Power BI in max 2 weeks.

**Comment by vichus1995** [comment]
Thanks for that, Bhavesh. 
I downloaded the latest pbiviz file (v1.1.1) and imported it in to the power BI file,But couldn't see any change from the issue I mentioned above.
Any reason for that?

**Comment by bhavesh-jadav** [comment]
If the custom visual is published on AppSource, then Power BI will always take the version from AppSource even if you use the .pbiviz file of latest version. For e.g. in this case, if you try to import v1.1.1 from GitHub, Power BI will take v1.1.0 because that is available on AppSource. And even after it is updated on AppSource it takes max 2 weeks to appear on Power BI. Till than Power BI will keep using old version. That is why it takes long time for any fix to deploy. I will add v1.1.1 to AppSource today and once it is approved by AppSource team, it will take max 2 weeks to finally reach you. More info available on below link.

[https://docs.microsoft.com/en-us/power-bi/developer/office-store](url)

**Comment by bhavesh-jadav** [comment]
Fixed in v1.1.1 now available on Power BI.
