### ISSUE TITLE
Date Field displays as MM generic instead of actual month: affects all reports published on Service

### ISSUE THREAD

**Issue by Drunprofits** [bhavesh-jadav/Advance-Card#25]
From late last week, Advance Card no longer displays date correctly: month is now shown as MM : this affects all the reports I have published back to mid October . I used Advance Card as a dated title on every page of hundreds of reports : these are all now showing months as MM only

The issue occurs in Power BI desktop, on Power BI Server and on all reports published from Power BI service: i.e right across all instantiations of Advance Card so problem must sit at source. Given this worked fine before the weekend, I can only assume you have changed this recently?

can you please fix or revert to the version that was working fine!!!!!!

I now have to stop using Advance Card as each daily report will have for example 28 MM 2018 instead of 28 November 2018
example attached

help and revolution hugely appreciated as I may now have to rework hundreds of pages to manually remove Advance Card*

Affects Power BI desktop and Power BI service and all historical reports containing Advance Card even though they were displaying correctly prior to recent changes or update to Advance card

**Expected behavior**
date should be displayed as 28 November 2018 which it used to do until last Friday or this Monday

occurs on all browers and on different Windows OS

**Screenshots**
see attached
**Desktop (please complete the following information):**
 - OS: [Windows 7 64bit: Windows 10 32 bit
 - Browser Chrome, IE, Firefox

![2018-11-27 10_33_21-uk markets mon 26nov 2018 - power bi desktop](https://user-images.githubusercontent.com/45169125/49141546-c1102880-f2ee-11e8-9c07-3efb203c48b8.jpg)

**Additional context**
![2018-11-28 09_19_57-gapsn splats tues 27 nov 18 - power bi desktop](https://user-images.githubusercontent.com/45169125/49141571-d2593500-f2ee-11e8-89d5-f3955d43c86d.jpg)
![2018-11-28 09_20_34-uk markets wed 14 nov 2018 - power bi](https://user-images.githubusercontent.com/45169125/49141614-e7ce5f00-f2ee-11e8-90db-cf9f362bea8c.jpg)

**Comment by bhavesh-jadav** [comment]
Hi @Drunprofits 

I apologize for the inconvenience.
Can you please give me following details.

- Which version of advance card are you using? go to format format pane About section for version.
- Are you using measure to display date? If then can you please share the DAX?

**Comment by bhavesh-jadav** [comment]
Hi @Drunprofits 

I have found the problem.
It was from the Power BI side. I am using formatting utility provided by Power BI team to format date and numbers and there was issue with their formatting utility library which they have fixed on 23 November. See below link.
https://github.com/Microsoft/powerbi-visuals-utils-formattingutils/commits/es2015

I will update Advance card with latest Formatting Util version and it will fix the problem. But it will take time to reach on Power BI due to Power BI Policy on when custom visual gets updated on AppSource and Power BI.

**Comment by Drunprofits** [comment]
ok but for clarity, the same problem occurs on Power BI Desktop as well as Service so local versions of Advance Card show MM. 

I assume that the Power BI Desktop App will also need an update to remove this error ?

 I am using Version: 2.64.5285.741 64-bit (November 2018). I might roll-back to an earlier version  to confirm as this anomaly only surfaced with the Nov update

Thank you for the very rapid follow-up and debugging: top work!

**Comment by bhavesh-jadav** [comment]
There is no need to update or rollback Power BI desktop. I will update
Advance Card and it will fix the issue.

If it was in my hand you could have gotten the update by tomorrow, but I
have to follow procedure as follows

1. Fix bugs and submit new version to Appsource for approval ( approval
takes 2-3 days).
2. After it gets approved on Appsource, it takes another 2 weeks for it be
appear on Power BI due to Power BI policy.

I apologise for any inconveniences.

**Comment by bhavesh-jadav** [comment]
This is fixed in v2.0.4
